language:
- node_js
- java
node_js:
- 14.5.0
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_script:
- gem install travis
script:
- chmod +x trigger-studio-build.sh
- bash -c "mvn -q -Dmaven.javadoc.skip=true clean package"
after_script: "./trigger-studio-build.sh"
env:
  global:
  - secure: e5joUnFNt4wLcT1U7tdHBaM5+vXs9QpACWFCuCI8qoQPcydAVb1cFh5vR0CyV7fT48lXrRtviQbw4SGaOBlQjX4gIfxFFaW/yeL/aKJ4v1KT3stlZPUUNsVhDSmYE5Xo9T/vE6ealk2VUrvkmreacQjAWRlWHGMnMq9jz+imOof05r4Fov7ezrXRVZ2Y0pZZU13V/thqIwFNZhH8dyDCxh8aP401mJBoQwtSDXnx9F5ty45GkeiInS0fFY3Mt6VWJWYYbf+pxXGf0PjxbTpnWSNG7Ij6/lNkwxwcjFdQLpvtpejNxw3qOhWo8tEIhtIc/xsk2K2eWcpaIASlHOgBfM7MQj91HokG2Pg0+uGfFCqqvC5uWTuYhWpbutppVnIHn9+qTfb7ScwlTZmfqvTbHCrpojdHwNgwFx4zfFPciyq3oW1ynXSsvPsfILlkt16tNUEsRL4ISVfuOFZw7hpBWVoJ8tUrD2QjrU18T43cSWIT3qfD03eDg33yDF0kHytFHrJcdTTQF96jR+qQwWdNIngn9RitgxQDjI+HOb3+54secYM5zINRtFqbKNDXPQaC6MWq8SFR2vOQh7RgBUC09aEws+rj9mWz0/Vcy6oUhCmQnsfx+qorB0jP7ExmQ23XqIxcqRWpj1FyJgRtjvliv05Xdm4sjIRiPkuBJskwxmQ=
