version: ~> 1.0
git:
  depth: 1
  quiet: true
language:
- java
jdk:
- openjdk11
branches:
  only:
  - develop
  - support/.*
  - master
notifications:
  irc:
    channels:
    - chat.freenode.net#craftercms
    use_notice: true
    skip_join: true
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
script:
  - bash -c "mvn -q -Dmaven.javadoc.skip=true clean package"
